version: '3'
services:
  express:
    command: ["npm", "run", "dev"]
    volumes:
      - ./express:/usr/src/app
    stdin_open: true
    tty: true
  strapi:
    stdin_open: true
    tty: true
  db:
    stdin_open: true
    tty: true
